stages:
  - test
  - package
  - deploy

before_script:
  - whoami
  - pwd

build-docker-img:
  stage: test
  variables:
      CNAME: swarm
      GIT_STRATEGY: none
  before_script:
    - docker info
    - pwd
  script:
    - docker build -t ${CNAME}:2.0 . # --no-cache
    - docker rm -f ${CNAME} & > /dev/null  2>&1
    - docker run --name ${CNAME} -p 8081:80 -it -d ${CNAME}:2.0 > /dev/null  2>&1
  environment:
    name: test
    url: http://${CNAME}
  only:
    - develop
    
