stages:
  - build
  - test
  - deploy

before_script:
  - pwd
  - ls .
  
build-docker-img:
  stage: build
  variables:
    CNAME: swarm.insa.gov.br
    GIT_STRATEGY: none
  cache:
    key: site-package
    policy: push
    paths:
      - /home/gitlab-runner/builds/3c304f9e/0/operations/frontpage-ui
  script:
    - chmod +x shell.sh 
    - ./shell.sh
    - docker build -t ${CNAME} .  #--no-cache
    - docker run --name ${CNAME} -p 8081:80 -it -d ${CNAME}
      # --progress=false
    #- docker tag ${CNAME}:2.0 docker-registry.insa.gov.br:5000/${CNAME}:2.0
    #- docker push docker-registry.insa.gov.br:5000/frontend-angular:2.0
  environment:
    name: build
    url: http://${CNAME}
  only:
    - master
  tags:
    - sades-shell


teste_build:
  stage: test
  variables:
    CNAME: swarm.insa.gov.br
    GIT_STRATEGY: none
  cache:
    key: site-package
    policy: pull  
  script: curl -L http://${CNAME} |grep Portal
  when: manual
  only:
    - master
  tags:
    - sades-shell
    

teste_vulnerabilities:
  stage: test
  script:
    - git clone https://github.com/docker/docker-bench-security.git
    - cd docker-bench-security
    - sh docker-bench-security.sh  
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2h20min
    paths:
      - /home/gitlab-runner/builds/3c304f9e/0/operations/frontpage-ui/docker-bench-security/docker-bench-security.sh.log
  only: 
    - master
  tags:
    - sades-shell

  