

stages:
  - test
  - package
  - deploy

before_script:
   - docker info 

build-docker-img:
   stage: test
   script:
     - docker build -t frontend-angular:2.0 . 
     - docker tag frontend-angular:2.0 docker-registry.insa.gov.br:5000/frontend-angular:2.0
     - docker push docker-registry.insa.gov.br:5000/frontend-angular:2.0
     
  
