stages:
  - build
  - test
  - pos-build
  - deploy
  

build-docker-img:
  stage: build
  variables:
    CNAME: swarm.insa.gov.br
    #CACHE_BUILD: "QU61MTD1"
    GIT_STRATEGY: none
  #cache:
  #  key: site-package
  #  policy: push
  #  paths:
  #    - /home/gitlab-runner/builds/${CACHE_BUILD}/0/operations/frontpage-ui
  before_script:
  - docker info
  - chmod +x shell.sh 
  - ./shell.sh
  script:
    - docker build -t ${CNAME} .  #--no-cache
    - docker run --name ${CNAME} -p 8081:80 -it -d ${CNAME}
  environment:
    name: build
    url: http://${CNAME}
  only:
    - master
  tags:
    - runner-shared-shell


teste_vulnerabilities:
  stage: test
  script:
    - git clone https://github.com/docker/docker-bench-security.git
    - cd docker-bench-security
    - sh docker-bench-security.sh  
  variables:
    CACHE_BUILD: QU61MTD1
    GIT_STRATEGY: none
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2h20min
    paths:
      - /home/gitlab-runner/builds/${CACHE_BUILD}/0/operations/frontpage-ui/docker-bench-security/docker-bench-security.sh.log
  only: 
    - master
  tags:
    - runner-shared-shell

teste_build:
  stage: test
  variables:
    CNAME: swarm.insa.gov.br
    GIT_STRATEGY: none
  cache:
    key: site-package
    policy: pull  
  script: curl -L http://${CNAME} |grep Portal
  when: delayed
  start_in: 1 minute
  only:
    - master
  tags:
    - runner-shared-shell

pre-production:
  stage: pos-build
  variables:
    CNAME: swarm.insa.gov.br
    #CACHE-BUILD: "QU61MTD1"
    GIT_STRATEGY: none
  #cache:
  #  key: site-package-push
  #  policy: push
  #  paths:
  #    - /home/gitlab-runner/builds/${CACHE-BUILD}/0/operations/frontpage-ui
  script:
    - docker tag ${CNAME} docker-registry.insa.gov.br:5000/${CNAME}
    - docker push docker-registry.insa.gov.br:5000/${CNAME}
  after_script:
   - chmod +x shell.sh 
   - ./shell.sh
  only: 
    - master
  tags:
    - runner-shared-shell

production:
  stage: deploy
  variables:
    CNAME: swarm.insa.gov.br
    GIT_STRATEGY: none
  #cache:
  #  key: site-package-push
  #  policy: pull
  script:
    - docker run --name ${CNAME} -p 8081:80 -it -d docker-registry.insa.gov.br:5000/${CNAME}
  when: delayed
  start_in: 1 minute
  only: 
    - master
  tags:
    - sades-prod-shell

    
  




  