stages:
  - test
  - build
  - deploy

before_script:
  - whoami
  - pwd

build-docker-img:
  stage: build
  variables:
      CNAME: swarm.insa.gov.br
      GIT_STRATEGY: none
  before_script:
    - docker info
    - pwd
  script:
    - cat <<EOF  docker=$(docker ps -a|grep '${CNAME}') \
      if [ -f  $docker ] \ 
      then \
      docker rm -f ${CNAME} \
      else \
      /dev/null 2>&1 \
      fi  \ 
      EOF
    - docker build -t ${CNAME}:2.0 . # --no-cache
   # - docker rm -f ${CNAME} # > /dev/null  2>&1
    - docker run --name ${CNAME}  -p 8081:80 -it -d ${CNAME}:2.0 
  environment:
    name: build
    url: http://${CNAME}
  only:
    - develop
    
