stages:
  - test
  - package
  - deploy

before_script:
  - whoami
  - pwd

build-docker-img:
  stage: test
  before_script:
    - docker info
    - pwd
  script:
    - docker build -t ${CNAME}:2.0 . # --no-cache
    - docker run --name ${CNAME} -p 8081:80 -it -d ${CNAME}:2.0
  environment:
    name: test
    url: http://${CNAME}:8081
  cache:
      key: site-package
      policy: push
      paths:
        - /home/gitlab-runner/builds/fb7da123/0/operations/frontpage-ui
    only:
      - develop
    
