image: node

stages:
  - test
  - package
  - deploy

before_script:
  - whoami
  - pwd

test site:
  stage: test
  script:
    -  npm install -g @angular/cli 
    -  npm install 
    -  ng server --host 0.0.0.0 --port 80 &

  
