stages:
  - build
  - test
  - deploy

before_script:
  - pwd
  - ls
  
build-docker-img:
  stage: build
  variables:
    CNAME: swarm.insa.gov.br
    GIT_STRATEGY: clone
  cache:
    key: site-package
    policy: push
    paths:
      - /home/gitlab-runner/builds/3c304f9e/0/operations/frontpage-ui
  script:
    - chmod +x shell.sh 
    - ./shell.sh
    - docker build -t ${CNAME} .  --no-cache
    - docker run --name ${CNAME} -p 8081:80 -it -d ${CNAME}
    #- docker tag ${CNAME}:2.0 docker-registry.insa.gov.br:5000/${CNAME}:2.0
    #- docker push docker-registry.insa.gov.br:5000/frontend-angular:2.0
  environment:
    name: build
    url: http://${CNAME}
  only:
    - master


teste_build:
  stage: test
  variables:
    CNAME: swarm.insa.gov.br
    GIT_STRATEGY: none
  cache:
    key: site-package
    policy: pull  
  script: curl -L http://${CNAME} |grep Portal
  when: manual
  only:
    - master
    

teste_vulnerabilities:
  stage: test
  script:
    - git clone https://github.com/docker/docker-bench-security.git
    - cd docker-bench-security
    - sudo sh docker-bench-security.sh
  only: 
    - master

  