stages:
  - build
  - test
  - pos-build
  - deploy
  

build-docker-img:
  stage: build
  variables:
    CNAME: "swarm.insa.gov.br"
    CACHE_BUILD: "QU61MTD1"
    GIT_STRATEGY: pull
  cache:
    key: site-package
    policy: push
    paths:
      - /home/gitlab-runner/builds/${CACHE_BUILD}/0/operations/frontpage-ui
  before_script:
  - docker info
  - chmod +x shell.sh 
  - ./shell.sh
  script:
<<<<<<< HEAD
    - docker build -t ${CNAME} .  #--no-cache
=======
    - docker build -t ${CNAME} .  --no-cache
>>>>>>> 82cd592dcbfce767a7bf65f904aec5ecf75d1029
    - docker run --name ${CNAME} -p 8081:80 -it -d ${CNAME}
  only:
    - develop
  tags:
    - runner-shared-shell


teste_vulnerabilities:
  stage: test
  script:
    - git clone https://github.com/docker/docker-bench-security.git
    - cd docker-bench-security
    - sh docker-bench-security.sh  
  variables:
    CACHE_BUILD: "QU61MTD1"
    GIT_STRATEGY: pull
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2h20min
    paths:
      - /home/gitlab-runner/builds/${CACHE_BUILD}/0/operations/frontpage-ui/docker-bench-security/docker-bench-security.sh.log
  only: 
    - develop
  tags:
    - runner-shared-shell

teste_build:
  stage: test
  variables:
    CNAME: "swarm.insa.gov.br"
    GIT_STRATEGY: pull
  cache:
    key: site-package
    policy: pull  
  script: curl -L http://${CNAME} |grep Portal
  when: delayed
  start_in: 1 minute
  only:
    - develop
  tags:
    - runner-shared-shell

pre-production:
  stage: pos-build
  variables:
    CNAME: "swarm.insa.gov.br"
    CNAME_PROD: "swarm-prod.insa.gov.br"
    CACHE_BUILD: "QU61MTD1"
    GIT_STRATEGY: none
  cache:
    key: site-package-push
    policy: push
    paths:
      - /home/gitlab-runner/builds/${CACHE_BUILD}/0/operations/frontpage-ui
  script:
    - docker tag ${CNAME} docker-registry.insa.gov.br:5000/${CNAME_PROD}
    - docker push docker-registry.insa.gov.br:5000/${CNAME_PROD}
<<<<<<< HEAD
  after_script:
=======
  only: 
    - master
  tags:
    - runner-shared-shell


clear_pro_production:
  stage: deploy
  variables:
    GIT_STRATEGY: pull
  script:
>>>>>>> 82cd592dcbfce767a7bf65f904aec5ecf75d1029
  - chmod +x shell.sh 
  - ./shell.sh
  only: 
    - master
  tags:
<<<<<<< HEAD
    - runner-shared-shell
=======
    - sades-prod-shell

>>>>>>> 82cd592dcbfce767a7bf65f904aec5ecf75d1029

production:
  stage: deploy
  variables:
    CNAME_PROD: swarm-prod.insa.gov.br
    GIT_STRATEGY: pull
<<<<<<< HEAD
  cache:
    key: site-package-push
    policy: pull
  before_script:
  - chmod +x shell.sh 
  - ./shell.sh
=======
>>>>>>> 82cd592dcbfce767a7bf65f904aec5ecf75d1029
  script:
    - docker run --name ${CNAME_PROD} -p 8081:80 -it -d docker-registry.insa.gov.br:5000/${CNAME_PROD}
  when: delayed
  start_in: 1 minute
  environment:
    name: build
<<<<<<< HEAD
    url: http://${CNAME}
=======
    url: http://${CNAME_PROD}
>>>>>>> 82cd592dcbfce767a7bf65f904aec5ecf75d1029
  only: 
    - master
  tags:
    - sades-prod-shell

    
  




  