stages:
  - test_app
  - build
  - test
  - pos-build
  - deploy
  
node_app:
  image: node
  stage: test_app
  before_script:
    #-  yum install sudo -y
    #-  curl -sL https://rpm.nodesource.com/setup_9.x | sudo -E bash -
    #-  yum install -y nodejs
    -  npm install -g @angular/cli@^7.2.2 broken-link-checker@^0.7.8 wait-on@^3.2.0
  script:
    -  npm install
    -  ng serve --host 0.0.0.0 --port 80 &
    -  wait-on http-get://localhost --timeout 90000
    -  blc --recursive --exclude-external http://localhost
  tags:
    - sades-prod-teste

vulnerabilities check:
  image: node
  stage: test_app
  script:
    - npm install -g snyk && npm install && snyk auth 5ce35e61-e5e5-46f3-9ed8-436ae6b026e1
    - snyk test --severity-threshold=high
    - snyk test --severity-threshold=medium
  tags:
    - sades-prod-teste

build-docker-img: &build
  stage: build
  variables:
    CNAME: "swarm.insa.gov.br"
    CACHE_BUILD: "QU61MTD1"
    GIT_STRATEGY: pull
  cache:
    key: site-package
    policy: push
    paths:
      - /home/gitlab-runner/builds/${CACHE_BUILD}/0/operations/frontpage-ui
  script:
    - chmod +x shell.sh 
    - ./shell.sh
    - docker build -t ${CNAME} .  --no-cache
    - docker run --name ${CNAME} -p 8081:80 -it -d ${CNAME}
  only:
    refs:
      - master
  tags:
    - runner-shared-shell

teste_vulnerabilities:
  <<: *build
  stage: test
  script:
    - git clone https://github.com/docker/docker-bench-security.git
    - cd docker-bench-security
    - sh docker-bench-security.sh  
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2h20min
    paths:
      - /home/gitlab-runner/builds/${CACHE_BUILD}/0/operations/frontpage-ui/docker-bench-security/docker-bench-security.sh.log
  
teste_build:
  <<: *build
  stage: test
  cache:
    policy: pull  
  script:
    - docker container ls | grep ${CNAME}
    - curl -L http://${CNAME} |grep Portal
  when: delayed
  start_in: 1 minute
  
pre-production:
  <<: *build
  stage: pos-build
  variables:
    CNAME: "swarm.insa.gov.br"
    CNAME_PROD: "portaldadesertificacao.insa.gov.br"
    GIT_STRATEGY: none
  script:
    - docker tag ${CNAME} docker-registry.insa.gov.br:5000/${CNAME_PROD}
    - docker push docker-registry.insa.gov.br:5000/${CNAME_PROD}
  
clear_pro_production: &pro_production
  <<: *build
  stage: deploy
  script:
  - chmod +x shell.sh 
  - ./shell.sh
  tags:
    - sades-prod-shell

production:
  <<: *pro_production
  variables:
    CNAME_PROD: portaldadesertificacao.insa.gov.br
  script:
    - docker run --name ${CNAME_PROD} -p 8080:80 -it -d docker-registry.insa.gov.br:5000/${CNAME_PROD}
  when: delayed
  start_in: 1 minute
  environment:
    name: build
    url: http://${CNAME_PROD}
      
  




  