stages:
  - test
  - package
  - deploy

before_script:
   - docker info 
   - pwd

build-docker-img:
  stage: test
  variables:
    CNAME: angular
    GIT_STRATEGY: none
  script:
     - docker build -t ${CNAME}:2.0 . # --no-cache
     - docker run --name ${CNAME} -p 8081:80 -it -d ${CNAME}:2.0 
    # - docker tag frontend-angular:2.0 docker-registry.insa.gov.br:5000/frontend-angular:2.0
    # - docker push docker-registry.insa.gov.br:5000/frontend-angular:2.0
  cache:
    key: site-package
    policy: push
    paths:
     - ./home/gitlab-runner/builds/
  only:
    - master
     
  

