stages:
  - test_app
  - build
  - test
  - pos-build
  - deploy
  

node_app:
  image: centos:centos7
  stage: test_app
  before_script:
    -  yum install sudo -y
    -  curl -sL https://rpm.nodesource.com/setup_9.x | sudo -E bash -
    -  yum install -y nodejs
    -  npm install -g @angular/cli@^7.2.2 broken-link-checker@^0.7.8 wait-on@^3.2.0
  script:
    -  npm install
    -  ng serve --host 0.0.0.0 --port 80 &
    -  wait-on http-get://localhost --timeout 90000
    -  blc --recursive --exclude-external http://localhost
  tags:
    - runner-shared-docker


build-docker-img:
  stage: build
  variables:
    CNAME: "swarm.insa.gov.br"
    CACHE_BUILD: "QU61MTD1"
    GIT_STRATEGY: pull
  cache:
    key: site-package
    policy: push
    paths:
      - /home/gitlab-runner/builds/${CACHE_BUILD}/0/operations/frontpage-ui
  before_script:
  - docker info
  - chmod +x shell.sh 
  - ./shell.sh
  script:
    - docker build -t ${CNAME} .  #--no-cache
    - docker run --name ${CNAME} -p 8081:80 -it -d ${CNAME}
  only:
    refs:
      - master
  tags:
    - runner-shared-shell


teste_vulnerabilities:
  stage: test
  script:
    - git clone https://github.com/docker/docker-bench-security.git
    - cd docker-bench-security
    - sh docker-bench-security.sh  
  variables:
    CACHE_BUILD: "QU61MTD1"
    GIT_STRATEGY: pull
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 2h20min
    paths:
      - /home/gitlab-runner/builds/${CACHE_BUILD}/0/operations/frontpage-ui/docker-bench-security/docker-bench-security.sh.log
  only:
    refs:
      - master
  tags:
    - runner-shared-shell

teste_build:
  stage: test
  variables:
    CNAME: "swarm.insa.gov.br"
    GIT_STRATEGY: pull
  cache:
    key: site-package
    policy: pull  
  script:
    - docker container ls | grep ${CNAME}
    - curl -L http://${CNAME} |grep Portal
  when: delayed
  start_in: 1 minute
  only:
    refs:
      - master
  tags:
    - runner-shared-shell

pre-production:
  stage: pos-build
  variables:
    CNAME: "swarm.insa.gov.br"
    CNAME_PROD: "portaldadesertificacao.insa.gov.br"
    CACHE_BUILD: "QU61MTD1"
    GIT_STRATEGY: none
  cache:
    key: site-package-push
    policy: push
    paths:
      - /home/gitlab-runner/builds/${CACHE_BUILD}/0/operations/frontpage-ui
  script:
    - docker tag ${CNAME} docker-registry.insa.gov.br:5000/${CNAME_PROD}
    - docker push docker-registry.insa.gov.br:5000/${CNAME_PROD}
  tags:
    - runner-shared-shell


clear_pro_production:
  stage: deploy
  variables:
    GIT_STRATEGY: pull
  script:
  - chmod +x shell.sh 
  - ./shell.sh
  tags:
    - sades-prod-shell

production:
  stage: deploy
  variables:
    CNAME_PROD: portaldadesertificacao.insa.gov.br
    GIT_STRATEGY: pull
  script:
    - docker run --name ${CNAME_PROD} -p 8080:80 -it -d docker-registry.insa.gov.br:5000/${CNAME_PROD}
  when: delayed
  start_in: 1 minute
  environment:
    name: build
    url: http://${CNAME_PROD}
  tags:
    - sades-prod-shell

    
  




  